import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AOSInit } from "@/lib/aos";
import GlobalStyles from "@/sass/GlobalStyles/GlobalStyles";
import Parallax from "@/lib/parallax";
const myFont = localFont({
  src: "../assets/fonts/PatrickHand-Regular.ttf",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AOSInit />
      <GlobalStyles>
        <Parallax>
          <body>{children}</body>
        </Parallax>
      </GlobalStyles>
    </html>
  );
}
