export const icons = {
  bees: require("./bees.png"),
  children: require("./children.png"),
  grass: require("./grass.png"),
  rainbow: require("./rainbow.png"),
  cloud1: require("./cloud-1.png"),
  cloud2: require("./cloud-2.png"),
  cloud3: require("./cloud-3.png"),
  cloud5: require("./cloud-5.png"),
  cloud6: require("./cloud-6.png"),
  sunshine_home1: require("./sunshine_home1.png"),
  slider_devider: require("./slider_devider.png"),
  activity: require("./activity.png"),
  kid_playing: require("./kid_playing.jpg"),
  img1: require("./img1.jpg"),
  footer_304: require("./footer-304.png"),
  blog_3: require("./blog_3.jpg"),
  img2: require("./img2.jpg"),
  banner1: require("./banner1.jpg"),
  banner2: require("./banner2.jpg"),
  banner3: require("./banner3.jpg"),
  logo_footer: require("./logo_footer.png"),
};
